export const TYPES = {
    LOAD_DATA: 'LOAD_DATA',
    STARTING_DATA: 'STARTING_DATA',
    IS_LOADING: 'IS_LOADING',
    INPUT_VALUE: 'INPUT_VALUE',
    TOGGLE_DATA: 'TOGGLE_DATA',
    CLASS_TOGGLE_LEFT: 'CLASS_TOGGLE_LEFT',
    CLASS_TOGGLE_RIGHT: 'CLASS_TOGGLE_RIGHT'
}